source 'https://github.com/VodafoneEgypt/Specs.git'
source 'https://github.com/CocoaPods/Specs'

use_frameworks!

target 'VFThirdPartySwift_Example' do
  pod 'VFThirdPartySwift', :path => '../'

  target 'VFThirdPartySwift_Tests' do
    inherit! :search_paths

  end
end
